title: SCALE A/V KB
copyright: digitalroots ©2025

disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
languageCode: en-us

security:
  enableInlineShortcodes: true

outputs:
  home: [HTML, RSS, print]
  section: [HTML, RSS, print]
  page: [HTML, RSS, print]
