repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # - id: no-commit-to-branch
      #   args: [-b main]
  # - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  #   rev: v1.7.7.23
  #   hooks:
  #     - id: actionlint
  #       additional_dependencies:
  #         - pyflakes
  #         - shellcheck-py
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
  # Breaks Hugo shortcut codes by escaping the less than sign
  # - repo: https://github.com/executablebooks/mdformat
  #   rev: 0.7.16
  #   hooks:
  #     - id: mdformat
  #       additional_dependencies:
  #         - mdformat-frontmatter
  #         - mdformat-gfm
  #         - mdformat-tables
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        additional_dependencies: ["@commitlint/config-conventional"]
        stages: [commit-msg]
